### ISSUE TITLE
MKDIR BUG

### ISSUE THREAD

**Issue by sugarleaf** [OpenOrbis/mira-project-archive#21]
WHEN NEW DIR, PERMISSION NO

**Comment by CrazyVoidProgrammer** [comment]
Also an issue on Ubuntu Virtual machine when using supplied Makefile

**Comment by ghost** [comment]
Use kern_mkdirat instead of sys_mkdir in kernel
The bug fix about thread not correctly jailbreak have maybe an impact on it too.

Fixed [here](https://github.com/OpenOrbis/oni-framework/pull/6).

**Comment by kiwidoggie** [comment]
This has been fixed by @theorywrong thank you so much for your contribution :D
