### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by Xaviertoor** [OpenOrbis/mira-project-archive#24]
I'm using the git clone --recurse-submodules https://github.com/OpenOrbis/mira-project.git, I did the make create as the Developer Guide but when I run make I get the following error.

/opt/mira-project/Firmware/Dependencies/oni-framework# make
Compiling src/oni/utils/memory/syscall.s ...
Compiling src/oni/utils/utils.s ...
Compiling src/oni/rpc/rpcserver.c ...
In file included from src/oni/rpc/rpcserver.c:1:0:
include/oni/rpc/rpcserver.h:6:23: fatal error: sys/types.h: No such file or directory
 #include <sys/types.h>
                       ^
compilation terminated.
Makefile:72: recipe for target 'build/src/oni/rpc/rpcserver.o' failed
make: *** [build/src/oni/rpc/rpcserver.o] Error 1

**Comment by Xaviertoor** [comment]
/opt/mira-project/Firmware/MiraFW# make BSD_INC=/opt/mira-project/Firmware/Dependencies/freebsd-headers/include ONI_FRAMEWORK=/opt/mira-project/Firmware/Dependencies/oni-framework/
Compiling MiraFW...
Creating Payload...

**Comment by pearlxcore** [comment]
How you fixed it

**Comment by Xaviertoor** [comment]
In my case mira is in /opt

1 - cd /op/mira-project/Firmware/Dependencies/oni-framework
make create
cd ../../MiraFW
make create

2 - cd /opt/mira-project/Firmware/MiraFW

make BSD_INC=/opt/mira-project/Firmware/Dependencies/freebsd-headers/include ONI_FRAMEWORK=/opt/mira-project/Firmware/Dependencies/oni-framework/

3 - cd /opt/mira-project/Firmware/Dependencies/oni-framework

make BSD_INC=/opt/mira-make project/Firmware/Dependencies/freebsd-headers/include ONI_FRAMEWORK=/opt/mira-project/Firmware/Dependencies/oni-framework/
