### ISSUE TITLE
All part is uploaded ?

### ISSUE THREAD

**Issue by ghost** [OpenOrbis/mira-project-archive#25]
Just a question, whats features work now and what is uploaded in this repository ?

**Comment by AbkarinoMHM** [comment]
The current features is useful for developers only, since now we have built in debugger work and also a log server for logging kernel messages, but shortly there will be a new release for end users with more features added.
Abkarino

**Comment by ghost** [comment]
Yeah, but developpers need to know what is already done for not make this 2 times.
