### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by helloitu** [OpenOrbis/mira-project-archive#27]
When execute /init_development_environment.sh return?:

cc1: error: command line option ‘-fcheck-new’ is valid for C++/ObjC++ but not for C [-Werror]
cc1: all warnings being treated as errors
Makefile:72: recipe for target 'build/src/oni/utils/sys_wrappers.o' failed
make: *** [build/src/oni/utils/sys_wrappers.o] Error 1
Creating directories...
Cleaning project...
Compiling src/crt0.s ...
Compiling src/mira/utils/hook.c ...
cc1: error: command line option ‘-fcheck-new’ is valid for C++/ObjC++ but not for C [-Werror]
cc1: all warnings being treated as errors
Makefile:87: recipe for target 'build/src/mira/utils/hook.o' failed
make: *** [build/src/mira/utils/hook.o] Error 1

**Comment by Xaviertoor** [comment]
Works fine for me, try install make gcc binutils automake

**Comment by helloitu** [comment]
yah, fixed updating the environment, upgrading gcc, and clang.
