### ISSUE TITLE
Sleep mode black screen

### ISSUE THREAD

**Issue by Cryptogenic** [OpenOrbis/mira-project-archive#31]
Upon restarting from sleep mode, the system will black screen.

**Comment by kiwidoggie** [comment]
This is also related to #32 crash, will keep this one open and close the other.

**Comment by ghost** [comment]
Request for tester,[Possible fix here](https://github.com/OpenOrbis/mira-project/commit/20c9d9b47f8eaf41129f908e7eba1ef9921991d5)

**Comment by Cryptogenic** [comment]
Possible fix does not seem to fix the issue on 5.05.

~Edit: Pause on this - may be an issue on my end~

Issue is still present on 5.05 at least.

**Comment by Cryptogenic** [comment]
Appears issue has been resolved by @kiwidoggie for both shutdown and wakeup/sleep mode. VTX-HEN seems to have this issue as well however, so this issue will persist if Mira is loaded alongside with Vortex's HEN payload. I'm closing the issue on here though as it has been fixed on Mira's side.

**Comment by CelesteBlue-dev** [comment]
May @kiwidoggie explain what code was causing the issue ?

**Comment by c0d3m4st4** [comment]
May @kiwidoggie explain what code was causing the issue ? 

Yes, please. Maybe the fix can be applied to VTX-HEN too?

**Comment by kiwidoggie** [comment]
@c0d3m4st4 race conditions on socket cleanup (rpc-server, logserver) would cause the panic, shutdown was fixed by just removing the shutdown callback (which didn't do anything btw, but apparently even using it breaks stuff?)

**Comment by mschumacher69** [comment]
Rest Mode works fine for me on VTX-HEN v1.7.

I use it from @Al-Azif's live host https://ithaqua.thegate.network/#5.05
