### ISSUE TITLE
[TTY Messages] Patching shellcore

### ISSUE THREAD

**Issue by Hereisme76** [OpenOrbis/mira-project-archive#35]
If someone could patch the shellcore we could see ps4 game's TTY messages.

**Comment by AbkarinoMHM** [comment]
Sorry what do you mean by ps4 game's TTY messages?

**Comment by Hereisme76** [comment]
@AbkarinoMHM you know the game developer log messages aka console output the same that Was In the target manager on ps3 and is for ps4 neighborhood app.

**Comment by kiwidoggie** [comment]
This will be accepted, as currently only `/dev/console` is redirected. A new feature is requested for opening numerous TTY streams, and is in development
