### ISSUE TITLE
VSH Freeze and Kernel crash when shutdown

### ISSUE THREAD

**Issue by ghost** [OpenOrbis/mira-project-archive#41]
At some moment, the VSH freeze (unable to open settings for example or some menu was "dead)
and when you try to shutdown the kernel panic.

**Comment by ghost** [comment]
This broken data sometime in the HDD "Unable to start the PS4" (and append only when i use Mira for debug with the klog) (I have changed the HDD 2 time with a new HDD so that can't be this)

**Comment by kiwidoggie** [comment]
This is also related to #32 but on shutdown, not resume and this appears to be a full crash, not just a freeze.
