### ISSUE TITLE
Reloadable/swappable HEN (Homebrew Enabler) 

### ISSUE THREAD

**Issue by ghost** [OpenOrbis/mira-project-archive#49]
Need an Reloadable / Swappable HEN (Homebrew Enabler)

**Comment by kiwidoggie** [comment]
Status update, HEN has been added, but is only enabled for 5.01 at the moment. Playing fPKG/Debug Homebrew packages currently does not work (does not crash, but just does not work) yet retail/trial packages work fine. Will continue to do further investigation.
