### ISSUE TITLE
Lifting screenshot restrictions

### ISSUE THREAD

**Issue by ghos7bear** [OpenOrbis/mira-project-archive#53]
I would like to request a feature to lift screenshot restrictions in applications. Many games forbid you from taking screenshots during movies and cutscenes, Persona 5 specifically doesn't let you screenshot anywhere at all. I love taking screenshots and its sad that I'm unable to without capture card.

**Comment by SecT0uch** [comment]
xvortex/ps4-vtx-hen

**Comment by SecT0uch** [comment]
Check xvortex/ps4-vtx-hen, there is a pull request by @Biorn1950 containing this feature
