### ISSUE TITLE
DLL API 

### ISSUE THREAD

**Issue by Cryptogenic** [OpenOrbis/mira-project-archive#64]
An API via DLL to interface with Mira and manage memory.

**Comment by kiwidoggie** [comment]
This has already been completed in the form of MiraLib MiraConnection and the connections Extensions found in MiraToolkit. This needs to be documented for future usage on a wiki somewhere.

https://github.com/OpenOrbis/mira-project/blob/feature/refactor1_2/Tools/MiraLib/MiraConnection.cs

https://github.com/OpenOrbis/mira-project/blob/feature/refactor1_2/Tools/MiraToolkit/Core/Extensions/MiraOrbisUtilsExtension.cs

https://github.com/OpenOrbis/mira-project/blob/feature/refactor1_2/Tools/MiraToolkit/Core/Extensions/MiraFileTransferExtension.cs

**Comment by kiwidoggie** [comment]
This has been made into MiraLib
