### ISSUE TITLE
Mira Desktop App

### ISSUE THREAD

**Issue by Cryptogenic** [OpenOrbis/mira-project-archive#65]
A desktop app to interact with Mira.

**Comment by kiwidoggie** [comment]
There are three options that I have weighed here. The first being .net core which has recently gained support for WPF and WinForms, .NET Core is C# but cross platform. The second is to use Mono, which has already proven to me at least to be a bit cumbersome. Then there's Qt which is a monster and a half to get building and running properly, and it is also written in a native language that may have issues in cross platform. Open for discussions @OpenOrbis/developers

**Comment by helloitu** [comment]
Did u read about electron? in my opinion its the best choice to build multiplataform, actually i has tested it in a payload sender, that runs very well on windows/mac and linux.

https://github.com/helloitu/PS4-Desktop-Payload-Sender
https://electronjs.org/
