### ISSUE TITLE
1.2.64 Baseline Testing

### ISSUE THREAD

**Issue by kiwidoggie** [OpenOrbis/mira-project-archive#66]
In order to ensure that everything is ready to get mainlined, consult https://ci.appveyor.com/project/kiwidoggie/mira-project/build/1.2.61

for your respective versions and write below

BUILD : 1.2.61
FW: 5.05/5.01/4.55/4.05
DESCRIPTION :
(Mira)
Suspend/resume : Working/Freeze/Panic
Shutdown : Working/Freeze/Panic
(Mira+HEN) 
Suspend/resume : Working/Freeze/Panic
Shutdown : Working/Freeze/Panic

@OpenOrbis/testers-405 : https://ci.appveyor.com/project/kiwidoggie/mira-project/build/1.2.61/job/ergnnny9g6x3vgi8/artifacts

@OpenOrbis/testers-455 https://ci.appveyor.com/project/kiwidoggie/mira-project/build/job/lyxm4q6ejbaxyplo/artifacts

@OpenOrbis/testers-505 https://ci.appveyor.com/project/kiwidoggie/mira-project/build/job/spo1o7jkx0bg3x9x/artifacts

**Comment by Spark-NV** [comment]
BUILD : 1.2.61
FW: 5.05
DESCRIPTION:
(Mira)
Suspend/resume : Working
Shutdown : Working
(Mira+HEN)
Suspend/resume : Freeze
Shutdown : Working

**Comment by Marcowerjr** [comment]
BUILD : 1.2.61
FW: 5.05
DESCRIPTION :
(Mira)
Suspend/resume : Working
Shutdown : Working
(Mira+HEN)
Suspend/resume : Freeze
Shutdown : Working

**Comment by LightningMods** [comment]
BUILD : 1.2.61
FW: 4.55
DESCRIPTION :.......
(Mira)
Suspend/resume : Panic
Shutdown : Working
(Mira+HEN)
Suspend/resume : Freeze

MORE INFO

--A user thread receives a fatal signal

--exception: 0xa0024402 (SYSTEM_SOFTWARE_TIMEOUT_ASYNC)
--proc ID: 40
--proc name: SceShellUI
--(Async exception from GPU/system. No thread information.)

Shutdown : Working

**Comment by ghost** [comment]
BUILD : 1.2.61
FW: 4.55
DESCRIPTION :.......
**(Mira)**
**Suspend/resume:** Partially work. Don't save state, but there is no freeze. Console start like turned on from scratch, using ps button on DS4.
End of log from going to suspend: 

`<118>[Syscore Umd] callback finished (0.00 msec)
<118>[Syscore Umd] Event id=SCE_UMD_SYSTEM_EVENT_REBOOT(0x6), phase=1 end
<118>[Syscore Umd] Event id=SCE_UMD_SYSTEM_EVENT_REBOOT(0x6), phase=0 start
<118>[Syscore Umd] Event id=SCE_UMD_SYSTEM_EVENT_REBOOT(0x6), phase=0 end
<118>[Syscore Umd] m_backupRestoreMode=0
<118>[DTL] Closed.
<118>[Syscore App] sceUmdReboot(0x8004000) => 0
<118>[SceSysCore mini] killall timeout 5[sec]...
<118>[SceSysCore mini] sceKernelPollEventFlag(reboot_flag): failed 80020010
<118>[SceSysCore mini] call reboot(8004000)`

**Shutdown** : Working

**(Mira+HEN)**
**Suspend/resume with/without game:** Partially work. Don't save state, but there is no freeze. Console start like turned on from scratch, using ps button on DS4. Used hen: vtx
**Shutdown** : Working

**Comment by nokodemus** [comment]
BUILD : 1.2.61
FW: 4.05
DESCRIPTION : CUH-1216A

MIRA:
Suspend/resume : working
Shutdown : working

MIRA + xvortex-HEN 1.3:
Suspend/resume : working
Shutdown : working

**Comment by pearlxcore** [comment]
BUILD : 1.2.61
FW: 5.05
DESCRIPTION :
(Mira)
Suspend/resume : Working
Shutdown : Working

(Mira+HEN)
Suspend/resume : Freeze
Shutdown : Working

**Comment by DarkElementPL** [comment]
BUILD : 1.2.61
DESCRIPTION : CUH-1216A
(Mira)
Suspend/resume: Working
Shutdown: Working
(Mira+HEN)
Suspend/resume: Freeze
Shutdown: Working

**Comment by DayVeeBoi** [comment]
BUILD: 1.2.61
FW: 4.55
DESCRIPTION: SLIM
(Mira)
Suspend/Resume: Broken
Shutdown: Working
(Mira+HEN)
Suspend/Resume: Broken
Shutdown: Working

Details:
**Mira**
Suspend/resume: -With Rest Mode setting "Keep Applications Suspended" enabled system crashes on wake up and goes through repair DB cycle on next powerup (it doesn't seem to matter whether an application is actually suspended or not).
-With Rest Mode setting "Keep Applications Suspended" disabled it seems to complete a regular shutdown and restart as from poweroff 

Shutdown: -Seems to work

**Mira+HEN**
Suspend/resume: -Same behaviour as Mira

Shutdown: -Same behaviour as Mira

**Comment by diggerdu** [comment]
BUILD : 1.2.61
FW: 5.05
DESCRIPTION:
(Mira)
Suspend/resume : Working
Shutdown : Working
(Mira+HEN)
Suspend/resume : Freeze
Shutdown : Working

**Comment by helloitu** [comment]
BUILD : 1.2.61
FW: 5.05
DESCRIPTION : the test has been launched in 

(Mira)
Suspend/resume : Freeze
Shutdown : Working
(Mira+HEN)
Suspend/resume : Freeze
Shutdown : Working

**Comment by kiwidoggie** [comment]
Closing in favor of a newer build.
