### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by kiwidoggie** [OpenOrbis/mira-project-archive#68]
We also need dedicated people to help with the localization process of Mira + Toolkit

**Comment by k0t99** [comment]
I know Russian I can help with this language.

**Comment by nokodemus** [comment]
I could add german and/or english if necessary 

How would you like to organize translation? Sth. like Transifex or just a simple phrases-*xml right here?

**Comment by lubek76** [comment]
I can help with slovak language ,czech language

**Comment by helloitu** [comment]
I can help with portuguese

**Comment by Marcowerjr** [comment]
I could help with Spanish

**Comment by pikami** [comment]
I can help with Lithuanian

**Comment by kotipuka01** [comment]
I can help with Bulgarian

**Comment by whooof** [comment]
I'll translate to polish.

**Comment by alanliu02** [comment]
I can help with Chinese.

**Comment by logock** [comment]
I can help with Hungarian

**Comment by krugdenis** [comment]
I can help with Russian

**Comment by Sato-Isolated** [comment]
i can help with french

**Comment by CrazyVoidProgrammer** [comment]
Thank you all, we will be in touch when we start this process!
