### ISSUE TITLE
App Persistent Storage

### ISSUE THREAD

**Issue by Cryptogenic** [OpenOrbis/mira-project-archive#76]
Mira would be a nice middle-man for homebrew apps to use for persistent storage. Each homebrew app could have a unique identifier which Mira would read and provide an API to the app to read/write from/to it's unique persistence directory.

This allows homebrews to use persistent storage without making an absolute mess of the filesystem by keeping it neat and organized via Mira.

**Comment by ghost** [comment]
Possibility:

Using the same method of OverlayFS, create a nullfs of the folder /data/HMBR00001 when app is mounted (and create the folder if he don’t exist)

**Comment by flatz** [comment]
there's builtin functionality for doing this (download0/download1 directories) available from app content module iirc
