### ISSUE TITLE
Unable to build MiraFileTransferPlugin

### ISSUE THREAD

**Issue by ema2ooo** [OpenOrbis/mira-project-archive#8]
i'm getting the following error while trying to build MiraFileTransferPlugin project 

2>    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.Makefile.Targets(143,5): error : cd ~/mira/Firmware/Plugins/MiraFileTransferPlugin;make create;make exited with code 2

**Comment by pearlxcore** [comment]
What is your setup?

**Comment by pearlxcore** [comment]
I think you need to setup the environment which i guess they haven’t uploaded yet

**Comment by ema2ooo** [comment]
thanks i found it in the developer.md 
ran scripts/init_development_environment.cmd but nothing gets copied to output folder
my setup is  vs2017 on windows 10 , linux ubuntu-16.04.2-server-amd64 (installed gcc , gdbserver ... etc)

build succeeds but no files to be copied , maybe i need to check output folder on remote linux vm
 
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.Makefile.Targets(140,5): warning : Build command not configured. Skipping...
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.Makefile.Targets(143,5): warning : Cannot copy file 'Oni_Orbis.elf', file not found on the remote system.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.Makefile.Targets(143,5): warning : Cannot copy file 'Oni_Orbis.bin', file not found on the remote system.

**Comment by ema2ooo** [comment]
![image](https://user-images.githubusercontent.com/491847/40110234-26ad8376-5908-11e8-9d58-8c6ce21147a9.png)
Found it Thanks , maybe the outpath set to wrong path
