### ISSUE TITLE
Delete star

### ISSUE THREAD

**Issue by chumblefish** [OpenOrbis/mira-project-archive#96]
Hi, I don't really know if this is the place to mention this, but a while ago I jailbroke a ps4 and found I kept losing game save data. I finally found the reason was that when I select a game to delete, and press the delete "star" buttton, not only the selected game and accompanying data is deleted, but game save data for every game is deleted, without any warning.

To me this is a bug. I restarted a lot of games (such as Shadow of Colussus and No Man's Sky) and replayed the same parts over and over to try to get to the point I had reached before I lost the data until eventually it just became a chore and the games were ruined.

**Comment by jogolden** [comment]
I don't believe this is an issue with Mira, possibly something to do with debug settings patch but I highly doubt it. I think the issue is with packages metadata not properly being set or something of that sort. I would try it with a non pirated game and see if it still works with payloads loaded.

**Comment by chumblefish** [comment]
Thanks for your reply. I didn't understand all of what you said, but just to clarify, the delete star option is only there when mira is loaded, and it deletes all save game data (including non-pirated games). I think the problem is that somebody felt that a star symbol next to delete somehow conveyed the info that all games would be affected, as if users could read this person's mind, or that a star was a universal symbol for "all games" or something. I know that's not a literal bug as such, but it's really careless (with all due respect to whoever programmed this stuff for people like me to use for free).
